#
#
# BOF
---

name: Standard workflow 
run-name: Standard workflow run by ${{ github.actor }}
on:
  push:
   branches-ignore:
     - 'main'
     - 'dependabot/*'
  workflow_dispatch:

env:
  MAVEN_CODE_PATH: ./maven
  MAVEN_SERVER_ID: github
  MAVEN_REGISTRY_URL: https://maven.pkg.github.com

defaults:
  run: 
    shell: bash

jobs:
  #
  preparation:
    runs-on: ubuntu-latest
    # 
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
  #
  validation:
    runs-on: ubuntu-latest
    needs: [ preparation ]
    #
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
  #
  scanning-trivy:
    runs-on: ubuntu-latest
    needs: [ validation ]
    env: 
      OUTPUTFILE: trivy-results.sarif
    #
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
      ## ---------------------------------------------------
      - name: Trivy Repo vulnerability scan
        # src: https://github.com/aquasecurity/trivy-action
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'sarif'
          output: ${{ env.OUTPUTFILE }}
          exit-code: '1'
          ignore-unfixed: true
          severity: 'MEDIUM,HIGH,CRITICAL'
      ## ---------------------------------------------------
      - name: Trivy Repo vulnerability scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ env.OUTPUTFILE }}
  #
  construction:
    runs-on: ubuntu-latest
    needs: [ scanning-trivy ]
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
      ## ---------------------------------------------------
      - name: Java Development Kit setup
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      ## ---------------------------------------------------
      - name: Build version
        id: buildVersion
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          DRY_RUN: true
          PRERELEASE_SUFFIX: build
          WITH_V: false
          PRERELEASE: true
      ## ---------------------------------------------------
      - name: Build with Maven
        run: |
          cd ${{ env.MAVEN_CODE_PATH }}
          mvn --batch-mode package --file pom.xml -Dversion=${{ steps.buildVersion.outputs.tag }}
     ## ---------------------------------------------------
     # improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@d682d5d68a398c90e9b35f8c564cd8e1918d6a24
        with:
          directory: ${{ env.MAVEN_CODE_PATH }}
  #
  testing:
    runs-on: ubuntu-latest
    needs: [ construction ]
    #
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
        
  publish:
    if: github.ref_name == 'development'
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: [ testing ]
    #
    steps: 
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
      ## ---------------------------------------------------
      - name: Java Development Kit setup
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
          server-id: ${{ env.MAVEN_SERVER_ID }}
     ## ---------------------------------------------------
      - name: Version
        id: releaseVersion
        if: github.ref_name == 'development'
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: false
          PRERELEASE: true
      ## ---------------------------------------------------
      - name: Publish Package
        id: publish
        if: ${{ steps.releaseVersion.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ env.MAVEN_CODE_PATH }}
          mvn versions:set -DnewVersion=${{ steps.releaseVersion.outputs.tag }}
          mvn --batch-mode deploy -DaltDeploymentRepository=${{ env.MAVEN_SERVER_ID }}::default::${{ env.MAVEN_REGISTRY_URL }}/${{ github.repository }} 
  pull-to-dev:
    if: github.ref_name != 'development'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: [ testing ]
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
      ## ---------------------------------------------------
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: development
          github_token: ${{ secrets.GITHUB_TOKEN }}
  #
  pull-request:
    if: github.ref_name == 'development'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: [ testing ]
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
      ## ---------------------------------------------------
      - name: Create Pull Request
        id: create-pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      ## ---------------------------------------------------
      - name: Check outputs
        if: ${{ steps.create-pull-request.outputs.pr_number }}
        run: |
          echo "Pull Request Number - ${{ steps.create-pull-request.outputs.pr_number }}"
          echo "Pull Request URL - ${{ steps.create-pull-request.outputs.pr_url }}"

...
# EOF