#
#
# BOF
---

name: Standard workflow 
run-name: Standard workflow run by ${{ github.actor }}
on:
  push:
   branches-ignore:
     - 'main'
  workflow_dispatch:

env:
  MAVIN_CODE_PATH: ./mavin
defaults:
  run: 
    shell: bash

jobs:
  #
  preparation:
    runs-on: ubuntu-latest
    # 
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
  #
  validation:
    runs-on: ubuntu-latest
    needs: [ preparation ]
    #
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
  #
  scanning-trivy:
    runs-on: ubuntu-latest
    needs: [ validation ]
    env: 
      OUTPUTFILE: trivy-results.sarif
    #
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
      ## ---------------------------------------------------
      - name: Trivy Repo vulnerability scan
        # src: https://github.com/aquasecurity/trivy-action
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'sarif'
          output: ${{ env.OUTPUTFILE }}
          exit-code: '1'
          ignore-unfixed: true
          severity: 'MEDIUM,HIGH,CRITICAL'
      ## ---------------------------------------------------
      - name: Trivy Repo vulnerability scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ env.OUTPUTFILE }}
  #
  construction:
    runs-on: ubuntu-latest
    needs: [ scanning-trivy, scanning-snyk ]
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
      ## ---------------------------------------------------
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      ## ---------------------------------------------------
      - name: Build with Maven
        run: |
          cd ${{ env.MAVIN_CODE_PATH }}
          mvn -B package --file pom.xml
     ## ---------------------------------------------------
     # improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  #
  testing:
    runs-on: ubuntu-latest
    needs: [ construction ]
    #
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
  #
  pull-request:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: [ testing ]
    steps:
      ## ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
      ## ---------------------------------------------------
      - name: Create Pull Request
        id: create-pull-request
        if: github.ref_name == 'development'
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      ## ---------------------------------------------------
      - name: Check outputs
        if: ${{ steps.create-pull-request.outputs.pr_number }}
        run: |
          echo "Pull Request Number - ${{ steps.create-pull-request.outputs.pr_number }}"
          echo "Pull Request URL - ${{ steps.create-pull-request.outputs.pr_url }}"

...
# EOF